### ISSUE TITLE
🐛 Bug Report: Synology Deployment Issues

### ISSUE THREAD

**Issue by Owl-Tec** [stonith404/pocket-id#105]
### Reproduction steps

Deploying pocket-id via my Synology results in the container not properly starting:
<img width="331" alt="Screenshot 2025-01-11 at 7 05 50 PM" src="https://github.com/user-attachments/assets/b10c7ec3-1b9d-4d4b-bf8e-0f3c3bb5082d" />

My Docker host is a Synology DS1621+ and I am running the pocket-id container through my reverse proxy (Nginx Proxy Manager) via Portainer.

Here is my configure file:
```
services:
  pocket-id:
    image: stonith404/pocket-id  # or ghcr.io/stonith404/pocket-id
    restart: unless-stopped
    env_file:
      - stack.env
    ports:
      - 3002:80
    volumes:
      - "/volume1/docker/storage/pocket-id/data:/app/backend/data"
    # Optional healthcheck  
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
```

Here are my environmental values:

- I had to change the default port from 3000 to 3002 as both port 3000 and 3001 are being used in my environment. 

<img width="1366" alt="Screenshot 2025-01-11 at 7 02 28 PM" src="https://github.com/user-attachments/assets/3d66252b-9a0b-4d68-949f-f4252081e960" />

### Expected behavior

Pocket-id should deploy itself as a typical docker container on my Synology. 

### Actual Behavior

Here is the output from Docker container:
```
Creating user and group...

passwd: password for pocket-id is unchanged

Changing password for pocket-id

New password: 

Starting frontend...

Starting backend...

Starting Caddy...

2025/01/12 01:08:26 GeoLite2 City database is up-to-date.

WRN | ts=1736644106.8758528 msg=failed to set GOMAXPROCS error=open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory 

WRN | ts=1736644106.9430258 msg=failed to set GOMAXPROCS error=open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory 

INF | ts=1736644106.9432714 msg=using config from file file=/etc/caddy/Caddyfile.trust-proxy 

INF | ts=1736644106.945159 msg=adapted config to JSON adapter=caddyfile 

INF | ts=1736644106.946377 logger=admin msg=admin endpoint started address=localhost:2019 enforce_origin=false origins=["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"] 

WRN | ts=1736644106.9467092 logger=http.auto_https msg=server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server server_name=srv0 http_port=80 

INF | ts=1736644106.9467788 logger=tls.cache.maintenance msg=started background certificate maintenance cache=0xc000052280 

INF | ts=1736644106.9474592 logger=tls.cache.maintenance msg=stopped background certificate maintenance cache=0xc000052280 

Error: loading initial config: loading new config: http app module: start: listening on :80: listen tcp :80: bind: permission denied

Error: caddy process exited with error: exit status 1

Listening on 0.0.0.0:3002
```

My guess looking at the logs is that Caddy is not happy but I am not sure what has to be tweaked on my end.

**Comment by stonith404** [comment]
Can you try to change the internal port of Pocket ID by setting the env variable `CADDY_PORT` to something different than `80`? Make sure to also change the exposed ports then:
```diff
ports:
-  -3002:80 
+  -3002:<your new port set in CADDY_PORT>
```

**Comment by Owl-Tec** [comment]
Thanks for getting back to me so quickly. Same issue occurs when I have the Caddy port:
```
Creating user and group...

addgroup: gid '101' in use

adduser: unknown group pocket-id-group

Starting frontend...

Starting backend...

Starting Caddy...

2025/01/12 16:13:24 GeoLite2 City database is up-to-date.

WRN | ts=1736698405.043951 msg=failed to set GOMAXPROCS error=open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory 

WRN | ts=1736698405.1079454 msg=failed to set GOMAXPROCS error=open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory 

INF | ts=1736698405.1082203 msg=using config from file file=/etc/caddy/Caddyfile.trust-proxy 

INF | ts=1736698405.1096957 msg=adapted config to JSON adapter=caddyfile 

INF | ts=1736698405.110596 logger=admin msg=admin endpoint started address=localhost:2019 enforce_origin=false origins=["//127.0.0.1:2019","//localhost:2019","//[::1]:2019"] 

INF | ts=1736698405.1108637 logger=tls.cache.maintenance msg=started background certificate maintenance cache=0xc0005c8600 

INF | ts=1736698405.11119 logger=tls.cache.maintenance msg=stopped background certificate maintenance cache=0xc0005c8600 

Error: loading initial config: loading new config: http app module: start: listening on :88: listen tcp :88: bind: permission denied

Error: caddy process exited with error: exit status 1

Listening on 0.0.0.0:3002
```

Here is the new config:
```
services:
  pocket-id:
    image: stonith404/pocket-id  # or ghcr.io/stonith404/pocket-id
    restart: unless-stopped
    env_file:
      - stack.env
    ports:
      - 3002:88
    volumes:
      - "/volume1/docker/storage/pocket-id/data:/app/backend/data"
    # Optional healthcheck  
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
```

<img width="1422" alt="Screenshot 2025-01-12 at 9 17 12 AM" src="https://github.com/user-attachments/assets/c8a42233-4e56-4f86-bf50-3ae8599a7414" />

**Comment by stonith404** [comment]
Can you try a port that is higher than 1023?

**Comment by Owl-Tec** [comment]
Okay, I got it working. I unfortunately, I had to run my container as root which is strange as the previous account I used PUID and PGID values was an admin account:
<img width="1757" alt="Screenshot 2025-01-12 at 9 33 02 AM" src="https://github.com/user-attachments/assets/e6367376-ef6e-4e7f-b14b-dab954d16a93" />

Let me play around some more. Unfortunately, Synologies sometimes have wonky permission issues when using Docker with them.

**Comment by Owl-Tec** [comment]
> Can you try a port that is higher than 1023?

I just tried this but I changed my PUID and PGID back to my previous account:
```
Creating user and group...

addgroup: gid '101' in use

adduser: unknown group pocket-id-group

Starting frontend...

Starting backend...

Starting Caddy...

2025/01/12 16:36:58 GeoLite2 City database is up-to-date.

WRN | ts=1736699818.639398 msg=failed to set GOMAXPROCS error=open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory 

WRN | ts=1736699818.7116194 msg=failed to set GOMAXPROCS error=open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory 

INF | ts=1736699818.7118292 msg=using config from file file=/etc/caddy/Caddyfile.trust-proxy 

INF | ts=1736699818.7134519 msg=adapted config to JSON adapter=caddyfile 

INF | ts=1736699818.71441 logger=admin msg=admin endpoint started address=localhost:2019 enforce_origin=false origins=["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"] 

INF | ts=1736699818.7149563 logger=http.log msg=server running name=srv0 protocols=["h1","h2","h3"] 

ERR | ts=1736699818.7150369 msg=unable to create folder for config autosave dir=/.config/caddy error=mkdir /.config: permission denied 

INF | ts=1736699818.715087 msg=serving initial configuration 

INF | ts=1736699818.715101 logger=tls.cache.maintenance msg=started background certificate maintenance cache=0xc000697200 

WRN | ts=1736699818.7152119 logger=tls msg=unable to get instance ID; storage clean stamps will be incomplete error=mkdir /.local: permission denied 

Successfully started Caddy (pid=45) - Caddy is running in the background

ERR | ts=1736699818.7153118 logger=tls msg=could not clean default/global storage error=unable to acquire storage_clean lock: creating lock file: open /.local/share/caddy/locks/storage_clean.lock: no such file or directory 

INF | ts=1736699818.7153215 logger=tls msg=finished cleaning storage units 

Listening on 0.0.0.0:3002
```

It looks like it is 100% a permission issue (via my Synology and Docker) and separate from your application.

**Comment by Owl-Tec** [comment]
Okay, I spent playing around with my Synology all morning and right now due to limitations with my Synology, Pocket ID has be run as root. That is not ideal but also not a big deal as well for me. Even if your account has administrator permissions or Docker run permissions, Caddy will not run properly. 

I tried the following with no success:
1. https://drfrankenstein.co.uk/step-2-setting-up-a-restricted-docker-user-and-obtaining-ids/
2. https://www.synoforum.com/threads/permissions-for-user-to-run-docker.3536/

Anyway, thanks for releasing such a cool project - I cannot wait to deploy with my environment.

**Comment by stonith404** [comment]
Okay I'm glad it's working now. I can't really help you with the root user issue because I don't own a Synology NAS but I think there should be a way that the container runs without root.

Btw, thanks for your sponsorship :) I didn't receive an email that you want to get mentioned in the release notes. Did you miss the email or do you not want to get mentioned?

**Comment by Owl-Tec** [comment]
> Okay I'm glad it's working now. I can't really help you with the root user issue because I don't own a Synology NAS but I think there should be a way that the container runs without root.

I think so, I created a post on the Caddy forum to get their thoughts on this issue:
- https://caddy.community/t/synology-permission-issues/29610

I also created a ticket with Synology as well.

The reason why I am being so persistent with this issue is because there are so many of us using our Synologies as our complete homelab and they are very beginner friendly.


> Btw, thanks for your sponsorship :) I didn't receive an email that you want to get mentioned in the release notes. Did you miss the email or do you not want to get mentioned?
Oh I forgot - I am fine with not being mentioned at the moment :~).

**Comment by tayden** [comment]
I managed to get things to spin up properly by adding the user mapping to the docker compose:

```
services:
  pocket-id:
    image: stonith404/pocket-id
    container_name: pocket_id
    user: ${PUID}:${PGID}
    restart: unless-stopped
    environment:
      CADDY_PORT: 2080
    volumes:
      - "./data:/app/backend/data"
    healthcheck:
      test: "curl -f https://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
```
