### ISSUE TITLE
🐛 Bug Report: Unknown Locations despite GEO DB being loaded?

### ISSUE THREAD

**Issue by eximo84** [stonith404/pocket-id#129]
### Reproduction steps

I have enabled my API key and pointing the environment at the DB but my audit log is showing unknown.  No errors in the logs.

My Compose

```
services:
  pocket-id:
    image: stonith404/pocket-id  # or ghcr.io/stonith404/pocket-id
    container_name: pocket-id
    hostname: pocket-id
    restart: unless-stopped
    env_file: .env
    ports:
      - 3080:88
    volumes:
      - "/dockerdata/storage/pocket-id:/app/backend/data"
    # Optional healthcheck  
    healthcheck:
      test: "curl -f http://localhost:88/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    networks:
      - default
      - reverse_proxy
  
networks:
  default:
    name: $MY_DEFAULT_NETWORK
    external: true
  reverse_proxy:
    name: $MY_REVERSEPROXY_NETWORK
    external: true
```

My .env

```
# GENERAL
MY_DEFAULT_NETWORK=internal_apps
MY_REVERSEPROXY_NETWORK=reverse_proxy
MY_DOMAIN=my.domain.com
TZ=Europe/London
PGID=XXX
PUID=XXX


# See the README for more information: https://github.com/stonith404/pocket-id?tab=readme-ov-file#environment-variables
PUBLIC_APP_URL=https://xyz.$MY_DOMAIN
TRUST_PROXY=true
MAXMIND_LICENSE_KEY=XXX
GEOLITE_DB_PATH=/app/backend/data/GeoLite2-City.mmdb
CADDY_PORT=88
```

![Image](https://github.com/user-attachments/assets/53978cd5-ed17-46a6-9f45-2326c31fc274)

![Image](https://github.com/user-attachments/assets/1d2c8ebe-7c9f-478f-a400-eb9bc48505f4)

![Image](https://github.com/user-attachments/assets/4843b53a-0556-4a9f-b6fd-1e16b986da3a)

### Expected behavior

audit log to show city or approx location

### Actual Behavior

audit log showing unknown
