### ISSUE TITLE
🐛 Bug Report:  Issue adding Passkey (An unknown error occurred!) ANDROID

### ISSUE THREAD

**Issue by ivoarch** [stonith404/pocket-id#147]
### Reproduction steps

Hi I have a issue when I try to setup my accout and add a passkey. 

## Reproduction steps

Go to `https://id.my.domain.com/login/setup` add passkey and 
I receive this message **"An unknown error occurred!"**.

I use Pixel 6 Pro (Android latest), my password manager is Bitwarden .

My `.env`

```
# See the README for more information: https://github.com/stonith404/pocket-id?tab=readme-ov-file#environment-variables
PUBLIC_APP_URL=https://id.my.domain.com
TRUST_PROXY=true
MAXMIND_LICENSE_KEY=""
PUID=1000
PGID=1000
```

My `docker-compose.yaml`

```
services:
  pocket-id:
    image: stonith404/pocket-id 
    restart: unless-stopped
    env_file: .env
    ports:
      - "3010:80"
    volumes:
      - "./data:/app/backend/data"
```

My `Caddyfile`

```
id.my.domain.com {
   import logging
   reverse_proxy 12.34.56.789:3010
}
```

I find this issue #126 but checking I have my `.env` setup correctly and url address also protocol http/https match good .

Docker container only report this

```
pocket-id-1  | [GIN] 2025/01/20 - 12:01:14 | 200 |    5.243006ms |   194... | GET      "/api/webauthn/register/start"
```

Any idea?

Thanks!

### Expected behavior

Add passkey success!

### Actual Behavior

An unknown error occurred!
