### ISSUE TITLE
🐛 Bug Report: An unknown error occurred on initial Passkey setup

### ISSUE THREAD

**Issue by truncsphere** [stonith404/pocket-id#154]
### Reproduction steps

Go to https://pocket-id.TLD/settings/account and click on "Add Passkey". Once I click on that I get `An unknown error occurred` . 
I tried this in FF as well in a private window for FF. I'm using Swag as my reverse proxy if that makes any difference. 

.env

```
PUBLIC_APP_URL=https://pocket-id.TLD
TRUST_PROXY=true
MAXMIND_LICENSE_KEY=
PUID=1000
PGID=1000 
```

Docker-compose
```
services:
  pocket-id:
    image: stonith404/pocket-id  # or ghcr.io/stonith404/pocket-id
    container_name: pocket-id
    restart: unless-stopped
    networks:
      - proxy
    env_file: .env
    #ports:
    #  - 3350:80
    volumes:
      - "./data:/app/backend/data"
    # Optional healthcheck  
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

networks:
  proxy:
    external: true
```

### Expected behavior

I was expecting Bitwardend to ask to save the passkey upon pressing "Add Passkey". 

### Actual Behavior

Get an error stating `An unknown error occurred`
