### ISSUE TITLE
🐛 Bug Report:  Something went wrong - Internal Error

### ISSUE THREAD

**Issue by wh450g** [stonith404/pocket-id#206]
### Reproduction steps

The behavior started some days back, and it is the same on different installed instances....

Pocket 0.27.x (and 0.28) installed in Debian 12 LXC container, Docker v27.5
certificate from internal CA (but also tested from Letsencrypt) via external Caddy on the same host, also in Docker

Pocket .env with PUBLIC_APP_URL=https://<public.dns.name> 

Caddyfile just the basic information:
``` 
<public.dns.name> {
        tls {
                dns cloudflare {$CLOUDFLARE_API_TOKEN}
                resolvers 1.1.1.1
        }
        reverse_proxy pocket:80

}
```

### Expected behavior

Login should be possible, and user or admin should see the admin ui.

### Actual Behavior

After initial setup, when user tries to login (or admin tries to login, it doesn't matter), 
the authentication dialog gets displayed, user is either using a YubiKey to authenticate or a passkey shared in Bitwarden, both are registered.
The user will get an error like this:

<img width="491" alt="Image" src="https://github.com/user-attachments/assets/dfe32600-e0fd-4aa3-bcf6-bdd202add0a1" />

In the log, I can see this error:
```
pocket  | [GIN] 2025/02/04 - 13:16:32 | 200 |    1.216696ms |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2025/02/04 - 13:16:32 | 200 |    1.495341ms |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2025/02/04 - 13:16:32 | 200 |    1.011824ms |       127.0.0.1 | GET      "/api/webauthn/credentials"
pocket  | [GIN] 2025/02/04 - 13:16:32 | 200 |    1.054359ms |       127.0.0.1 | GET      "/api/webauthn/credentials"
pocket  | Axios error: /repos/stonith404/pocket-id/releases/latest - Request failed with status code 403
pocket  | Axios error: /repos/stonith404/pocket-id/releases/latest - Request failed with status code 403
pocket  | [GIN] 2025/02/04 - 13:17:26 | 200 |     376.075µs |       127.0.0.1 | GET      "/api/application-configuration"
```

### Version and Environment

Pocket 0.27.x (and 0.28) installed in Debian 12 LXC container, Docker v27.5, Caddy running in Docker on the same host (ghcr.io/caddybuilds/caddy-cloudflare:latest)

### Log Output

```
pocket  | [GIN] 2025/02/04 - 13:16:32 | 200 |    1.216696ms |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2025/02/04 - 13:16:32 | 200 |    1.495341ms |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2025/02/04 - 13:16:32 | 200 |    1.011824ms |       127.0.0.1 | GET      "/api/webauthn/credentials"
pocket  | [GIN] 2025/02/04 - 13:16:32 | 200 |    1.054359ms |       127.0.0.1 | GET      "/api/webauthn/credentials"
pocket  | Axios error: /repos/stonith404/pocket-id/releases/latest - Request failed with status code 403
pocket  | Axios error: /repos/stonith404/pocket-id/releases/latest - Request failed with status code 403
pocket  | [GIN] 2025/02/04 - 13:17:26 | 200 |     376.075µs |       127.0.0.1 | GET      "/api/application-configuration"
```

**Comment by kmendell** [comment]
@wh450g I think the error you are seeing, Is unrelated (well maybe) i think that is just the update checker, and it cant seem to get to the repo by the looks of it. Are these air gapped containers? or do they have internet access?

**Comment by wh450g** [comment]
The container have full (outbound) internet access (behind a firewall, but allow all to outbound)
The error in the log is always logged when the login error occurs for the user... watching the log, you can instantly see the entries when a user provides his passkey.

**Comment by kmendell** [comment]
@wh450g Can you share the docker compose file for pocket id and caddy?

**Comment by wh450g** [comment]
@kmendell sure, see below, I use 2 different compose file for it in their respective folder, but the two containers are the only ones running on the LXC:

caddy compose.yml
```
---
services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./data/Caddyfile:/etc/caddy/Caddyfile:rw
      - ./data/caddy-data:/data
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    networks:
      - frontend

networks:
  frontend:
    external: true
```

pocket id compose.yml
``` 
---
services:
  pocket-id:
    image: stonith404/pocket-id  # or ghcr.io/stonith404/pocket-id
    container_name: pocket
    restart: unless-stopped
    env_file: .env
      #ports:
      #- 3000:80
    volumes:
      - /home/username/pocket/data:/app/backend/data
    # Optional healthcheck
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

    networks:
      - frontend

networks:
  frontend:
    external: true
```
